### ISSUE TITLE
Verificar suporte a internacionalização

### ISSUE THREAD

**Issue by guipimenta** [guipimenta/GabariteiProject#11]
Verificar o suporte de internacionalização do Rails e Angular. Se possível, colocar no projeto para aumentar a abrangência da plataforma: cursos de inglês, uso no exterior.

**Comment by Revokee** [comment]
Se vocês estiverem codando em inglês pode ser fácil, se estão codando em português vai ser mais díficil. Dependendo do número de Strings "fixas" em páginas pode ser um trabalho bem chato.

**Comment by guipimenta** [comment]
É por isso que a gente queria fazer logo no começo. Nossa principal argumentação é: se quisermos utilizar a ferramenta em uma escola de inglês, não faria sentido só ter disponível em português. Ou, se fizermos tudo em inglês, como utilizar em colégios brasileiros?

**Comment by guipimenta** [comment]
Acho que o Angular já tem algum tipo de suporte:
https://docs.angularjs.org/guide/i18n

**Comment by guipimenta** [comment]
Aliás, parace ser bem simples:
https://youtu.be/GUQQcexCKPU?t=5m46s

**Comment by mizoguti** [comment]
É tranquilo implementar a internacionalização usando o angular-translate e essa ideia: https://medium.com/ruby-on-rails/maintainable-i18n-with-rails-and-angularjs-f3b2542a1980

Eu implementei isso no branch data-import-test. A discutir na próxima reunião.
