### ISSUE TITLE
Typescript x Coffee x Dart x Javascript

### ISSUE THREAD

**Issue by guipimenta** [guipimenta/GabariteiProject#13]
Padronizar desenvolvimento em uma das tecnologias

**Comment by mizoguti** [comment]
Eu acho que essa issue entra em conflito com a issue de TypeScript. Aparentemente o TypeScript sempre compila em um JavaScript puro, então usar o Coffee e TypeScript num mesmo projeto seria meio incoerente.

A gente teria que optar entre TypeScript, JavaScript puro ou Coffee. Talvez podemos considerar Dart também: https://www.dartlang.org

**Comment by guipimenta** [comment]
Justo, de noite, tava meio sonado.. ahaha. Vou deletar o outro. Mas acho importante a gente pensar para discutir na quarta.

**Comment by guipimenta** [comment]
O problema que encontrei no typescript:
tem um gem que compila no asset pipeline, mas ela da erro quando uma referência não foi encontrada. Ai temos que baixar uma bilbioteca de descritores para o type, fique meio confuso e não consegui fazer funcionar ahahah

**Comment by guipimenta** [comment]
A única maneira que consegui usar o typescript é rodar o compilador fora do asset pipeline, tipo, ir no terminal e rodar manualmente o compilador, depois de ele transformar em javascript, o assets pipeline inclui automaticamente

**Comment by guipimenta** [comment]
do dart não sei quase nada... ahah, preciso pesquisar
