### ISSUE TITLE
Converter arquivos angular em coffeescript

### ISSUE THREAD

**Issue by guipimenta** [guipimenta/GabariteiProject#14]
Eu começei codando em javascript puro a parte angular do projeto. Temos que "converter" para coffee

**Comment by Revokee** [comment]
Qual a vantagem?

**Comment by guipimenta** [comment]
A gente tinha decidido utilizar por padrão o CoffeeScript, mas descobri que isso vai dar muito problema com as ferramentas de teste. Vou fechar esse ticket
