### ISSUE TITLE
Organizar código

### ISSUE THREAD

**Issue by mizoguti** [guipimenta/GabariteiProject#19]
Organizar o código colocando comentários que o dividem em seções e que expliquem o que estamos fazendo.

**Comment by guipimenta** [comment]
Acho que  a gente pode fazer algo do tipo sugerido no styleguide:

https://github.com/johnpapa/angular-styleguide#style-y141

Melhor que ter um único arquivo controller.js gigante, além disso, minimiza problemas de conflito na hora do merge

**Comment by guipimenta** [comment]
Além disso, acho que devemos adotar jsdoc e o yard para deixar tudo bem documentado:  
[jsdoc Angular Flavor](https://github.com/angular/angular.js/wiki/Writing-AngularJS-Documentation)
[Yardoc Ruby Doxigen](http://yardoc.org/)

**Comment by mizoguti** [comment]
Hum boa! Vou dar uma olhada e começar a usar já então.
