### ISSUE TITLE
Refatoração código angular

### ISSUE THREAD

**Issue by guipimenta** [guipimenta/GabariteiProject#21]
Nós deveríamos separar nosso código javascript dentro de pastas, para ficar mais fácil de encontrar os arquivos quando precisarmos.

**Comment by mizoguti** [comment]
Eu organizei os arquivos angular em uma estrutura "folder-by-type", mas acabei de verificar que nosso styleguide sugere a estrutura "folder-by-feature", como o Gui tinha feito. Assim, vou reestruturar os arquivos. O styleguide também sugere mantermos os arquivos de teste ao lado dos arquivos principais.
