### ISSUE TITLE
Integrar associações do Active Record com Angular

### ISSUE THREAD

**Issue by mizoguti** [guipimenta/GabariteiProject#24]
Precisamos analisar como realizar os CRUDs levando em conta as associações entre tabelas.

**Comment by guipimenta** [comment]
Eu já estou trabalhando nisso na verdade, ahaha. Acho que o jeito mais justo é utilizar o próprios Resources do Angular, ai por exemplo, se a gente precisa relacionar subjects com questions, basta utilizar a injeção de dependências do Angular para injetar um resource Subjects dentro do controller de Questions, algo assim:

```
QuestionsController.$inject = ['Question', 'Subject']

function QuestionController(Question, Subject) {
   var vm = this;
   vm.subjects = Subject.get();
}
```

e na view:

```
<select id="Subjects">
  <option ng-repeat="subject in Ctrl.subjects">
    {{subject.name}}
  </option>
</select>
```

O único inconveniente é que a gente talvez tenha que efetuar uma tradução do nome para o id do subject, que é o que o rails usa.

**Comment by mizoguti** [comment]
Ah beleza! Me avisa se vc precisar de ajuda com a parte do Active Record então.

**Comment by guipimenta** [comment]
Por enquanto está tranquilo, mas talvez nas relações polimórficas talvez fique um pouco mais tricky.

**Comment by guipimenta** [comment]
Beleza, aparentemente funcionando!
