### ISSUE TITLE
Complementar CRUD de Subjects

### ISSUE THREAD

**Issue by mizoguti** [guipimenta/GabariteiProject#27]
O CRUD de subjects hoje não leva em conta a sub-tabela de áreas (Fields). Podemos criar um CRUD único para os dois modelos (quando se cria uma matéria, podem-se criar as áreas junto).

**Comment by guipimenta** [comment]
Boa, tinha esquecido, eu faço isso!

**Comment by guipimenta** [comment]
Feito!
