### ISSUE TITLE
Trocar o banco de dados

### ISSUE THREAD

**Issue by guipimenta** [guipimenta/GabariteiProject#3]
Atualmente usamos o banco de dados padrão SQLite. O banco de dados não é apropriado para aplicações Web. Refatorar para usar o MySQL.

**Comment by mizoguti** [comment]
Eu crie o branch "mysql-integration" e modifiquei o Gemfile e o database.yml para se conectar com o MySQL. Eu usei o MySQL 5.6.25 usando o root e sem senha. Mudar o database.yml se necessário.

Rodem o projeto nesse branch e vejam se funciona na máquina de vocês. Não esqueçam de rodar "rake db:create". Assim que vocês verificarem que funciona, fechamos a issue.
