### ISSUE TITLE
Relacionamento question e subject

### ISSUE THREAD

**Issue by guipimenta** [guipimenta/GabariteiProject#33]
Caso de uso interessante:
1. Crio um subject A 
2. Crio uma pergunta B com subject A
3. Deleto subject A
4. A pergunta deve ser deletada? Ou não devemos permitir deletar o subject A caso ainda existam perguntas relacionadas ao subject escolhido?

**Comment by mizoguti** [comment]
Esse problema não envolveria só as questões, tem também todas as outras tabelas que referenciam subjects/fields, como cursos e conteúdos… Acho que se um subject/field for deletado, a gente deveria deletar junto todos as entidades que dependem dele, mas alertando o utilizador de que essa ação é irreversível e pedindo uma confirmação antes.

**Comment by guipimenta** [comment]
Resolvido: agora ao deletar um subject relacionado a duas questões, essas questões serão deletadas.
