### ISSUE TITLE
Terminar modelagem do banco de dados.

### ISSUE THREAD

**Issue by guipimenta** [guipimenta/GabariteiProject#5]
Devemos terminar a modelagem do banco de dados para começar a desenvolver as features do projeto.

**Comment by mizoguti** [comment]
Eu terminei a modelagem do banco de dados. Eu fiz push no branch "database-schema" e coloquei os documentos no Drive. No seeds.rb, eu coloquei um pequeno teste. Vou deixar vocês darem uma olhada antes de fechar a issue (discutimos no próximo encontro).

**Comment by guipimenta** [comment]
Boa Leo!
Vou dar uma olhada amanhã quando tiver mais tempo!

**Comment by guipimenta** [comment]
Ow Leo, se você terminou com o branch mysql, depois deleta ele, para deixar o repositório mais clean!

**Comment by guipimenta** [comment]
Ow Leo, mais uma coisa, você chegou a verificar se suas alterações alteraram a forma dos controllers que já estavam implementados funcionar?

**Comment by guipimenta** [comment]
Acho que vai ter que dar o merge para eu acertar os testes, vc deu branch no master que não tinha os testes feitos ainda... :(

Enfim, ficou top a implementação! Gostei!
Único comentário que tenho a fazer é que talvez como nosso projeto é de engenharia de software, seria legal deixar alguns comentários nos modelos. Fica mais fácil para entender.

**Comment by mizoguti** [comment]
Então, eu ainda não mexi nos controllers que estavam implementados. É evidente que ia quebrar algumas coisas, visto que a gente mudou as relações... Eu vou adaptar o código que já existe pra esse novo modelo e aproveito pra fazer o merge pra integrar com os testes.

Hehe, você tem razão, vou colocar uns comentários no código e no PDF.

**Comment by guipimenta** [comment]
Leo, acho que está faltando algumas coisas no banco:
- Se a gente for montar um profile do user, está faltando os campos dessas informações
- O model question não tem mais o campo de relacionamento com o subject, apesar de ter o relacionamento.

**Comment by mizoguti** [comment]
Mal, eu ainda não consegui vasculhar todos os casos de uso pra pegar os campos de cada model, vou fazer isso agora.

Eu adicionei o campo de subjects no model question. Adaptei também o que já tinha sido implementado, pois antes a gente considerava que uma questão tinha uma única matéria, e hoje ela pode ter várias. Talvez a gente tenha que mudar isso ainda, fiz uma solução provisória pra poder ver o todo funcionando.
